// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaseuOusfGuCMTtnNPxq3aRT7YUXtF2SU',
    appId: '1:127060770876:web:c883d9f6a1077ee3fb0339',
    messagingSenderId: '127060770876',
    projectId: 'coocoo-1db65',
    authDomain: 'coocoo-1db65.firebaseapp.com',
    storageBucket: 'coocoo-1db65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtt_5ThSuxZoEmH31i9yJ4loEcr3fh2L4',
    appId: '1:127060770876:android:8c0498647d832556fb0339',
    messagingSenderId: '127060770876',
    projectId: 'coocoo-1db65',
    storageBucket: 'coocoo-1db65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAam2Rl-1dKuA_MVaQlGbNFqZRozd-W78c',
    appId: '1:127060770876:ios:5c3af0f16805fa18fb0339',
    messagingSenderId: '127060770876',
    projectId: 'coocoo-1db65',
    storageBucket: 'coocoo-1db65.appspot.com',
    iosBundleId: 'com.example.coocoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAam2Rl-1dKuA_MVaQlGbNFqZRozd-W78c',
    appId: '1:127060770876:ios:5c3af0f16805fa18fb0339',
    messagingSenderId: '127060770876',
    projectId: 'coocoo-1db65',
    storageBucket: 'coocoo-1db65.appspot.com',
    iosBundleId: 'com.example.coocoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaseuOusfGuCMTtnNPxq3aRT7YUXtF2SU',
    appId: '1:127060770876:web:9306065decc6cd96fb0339',
    messagingSenderId: '127060770876',
    projectId: 'coocoo-1db65',
    authDomain: 'coocoo-1db65.firebaseapp.com',
    storageBucket: 'coocoo-1db65.appspot.com',
  );
}
